"use strict";
/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var styles = [".login-outer-container[_ngcontent-%COMP%] {\r\n  min-height: 640px;\r\n\r\n  .login-inner-container {\r\n    position: absolute;\r\n    left: 50%;\r\n    top: 50%;\r\n    transform: translate(-50%, -50%);\r\n    -moz-transform: translate(-50%, -50%);\r\n    -webkit-transform: translate(-50%, -50%);\r\n    width: 450px;\r\n    padding: 8em 5em 5em;\r\n\r\n    h1 {\r\n      text-align: center;\r\n      margin-bottom: 30px;\r\n    }\r\n\r\n    .logo-container {\r\n      border-radius: 50%;\r\n      width: 150px;\r\n      height: 150px;\r\n      position: absolute;\r\n      top: -75px;\r\n      left: 50%;\r\n      -webkit-transform: translate(-50%, 0%);\r\n\r\n      img {\r\n        max-height: 125px;\r\n        max-width: 125px;\r\n      }\r\n    }\r\n\r\n    .session-expired {\r\n      text-align: center;\r\n    }\r\n\r\n    button {\r\n      width: 100%;\r\n      margin: 30px 0 0;\r\n    }\r\n\r\n    .dark_text {\r\n      color: #c5c5c5;\r\n      font-size: 9pt;\r\n    }\r\n\r\n    .title_text {\r\n      color: #7b7a79;\r\n      font-size: 10pt;\r\n      font-weight: bold;\r\n    }\r\n\r\n  }\r\n}"];
exports.styles = styles;
//# sourceMappingURL=login.component.scss.shim.ngstyle.js.map